### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by letienne** [CiscoDevNet/intersight-powershell#31]
Hello,

I was trying to use this module but I am unfortunately not able to get past the configuration step.

It seems I am unable to query my local appliance (running 1.0.9-361). The error appears to be the same with all get- methods I tried.

Any idea what I am doing wrong?

Thanks !

```
PS C:\Users\admin> get-module -name intersight.powershell

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Binary     1.0.9.5208            intersight.powershell               {Get-IntersightAaaAuditRecord, Get-IntersightAaaRetentionConfig, Get-Inter…

```

```

PS C:\Users\admin> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.4
PSEdition                      Core
GitCommitId                    7.1.4
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

```
PS C:\Users\admin> import-module intersight.powershell
PS C:\Users\admin> $onprem = @{
>>     BasePath = "https://my.appliance.my.domain/"
>>     ApiKeyId = "redacted"
>>     ApiKeyFilePath = "C:\\temp\\key.txt"
>>     HttpSigningHeader =  @("(request-target)", "Host", "Date", "Digest")
>>     SkipCertificateCheck = $True
>> }
PS C:\Users\admin> Set-IntersightConfiguration @onprem
```
```
PS C:\Users\admin> Get-Intersightntppolicy -name aaa
Get-IntersightNtpPolicy: Object reference not set to an instance of an object.
PS C:\Users\admin> $Error[0].Exception.StackTrace
   at Intersight.PowerShell.GetCmdletBase.ProcessRecord() in /home/jenkins/workspace/Release-IS-Powershell-Module/src/github.com/cisco-intersight/powershell-generator-intersight/generated/Intersight.PowerShell_1.0.9.5208/src/CmdletBase/GetCmdletBase.cs:line 115
   at System.Management.Automation.CommandProcessor.ProcessRecord()
```

**Comment by savithamr** [comment]
I couldn't reproduce the error in the www.intersight.com setup.

Do you get the same error when you run Get-IntersightConfiguration cmdlet?
Can you try the API calls in https://my.appliance.my.domain/apidocs 
Under the "API Reference" try any GET method and provide the output.

**Comment by Ghufz** [comment]
Hi letienne,
Can you please confirm the same behavior with the latest available module.
If you get the exception same like before ?
Can you run the below cmdlet and share the result.
```powershell
Get-IntersightConfiguration
Get-IntersightNtpPolicy

New-IntersightOrganizationOrganization -Name TestOrg
````

**Comment by letienne** [comment]
Unfortunately I still get the same issue:

```
PS C:\Users\x> Get-IntersightConfiguration

BasePath                : https://intersight.mylocalfqdn/
ApiKeyId                : <redacted>
ApiKeyFilePath          : C:\\temp\\key.txt
ApiKeyPassPhrase        :
Proxy                   :
HashAlgorithm           : SHA256
HttpSigningHeader       : {(request-target), Host, Date, Digest}
SignatureValidityPeriod : 0


PS C:\Users\x> Get-IntersightNtpPolicy
Get-IntersightNtpPolicy: Object reference not set to an instance of an object.
PS C:\Users\x> New-IntersightOrganizationOrganization -Name TestOrgToDelete
New-IntersightOrganizationOrganization: Object reference not set to an instance of an object.
```

And I have the latest version:

```
PS C:\Users\x> get-module -name intersight.powershell

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Binary     1.0.9.5313            Intersight.PowerShell               {Get-IntersightAaaAuditRecord, Get-IntersightAaaR…

```

Is there any way to troubleshoot where the nullpointerexception occurs?

**Comment by Ghufz** [comment]
@letienne [letienne](https://github.com/letienne)
Are you able to get the MO details using the inbuilt rest client with Intersight web?

**Comment by vvb** [comment]
closing for inactivity. Please re-open if you are still facing this issue.
